= Changes =

== Enable a command only when necessay ==

It is a good UI rule to disable a command when it is not possible
to execute it. This should be the case with the copy commands in the
GrepView in case no text is selected.

So I went for a quest in the wonderful world of eclipse extension points
to discover that it ain't easy...

=== Commands and handlers ===

My first shot with the pop-up menu in the grep view was to use two extension points:

1. a *menu* to list all commands to be shown in the popup
2. the *commands* listed in the menu above, each pointing to a default handler

but when I tried to add some conditions on the command enable I found out
that I actually need to define a *handler* for each command and add there the
enabledWhen clause.

=== Core expressions ===

Conditional enable is achieved using core expressions, which are just a
series of nested XML nodes that allow to evaluate and combine conditions.
e.g. there are handy pre-defined nodes to check if the current structured
selection is empty, but it does not work for a text selection.

So I used a test node, which accepts a property name to be evaluated, in this case:

`com.github.fabeclipse.textedgrep.GrepView.nonEmptyTextSelection`

the property is defined by the same grep plugin by extending:

`org.eclipse.core.expressions.propertyTesters`

and defining the property `nonEmptyTextSelection` in the
`com.github.fabeclipse.textedgrep.GrepView` namespace.

A java class specified in the extension point is then responsible for
evaluating this property when the framework requests it,
that is when the menu is about to be displayed and its handler's
core expression must be computed.
